
GET http://localhost:3001/api/notes

###
POST  http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"Smotott",
    "important":"false"
}

###
PUT  http://localhost:3001/api/notes/64d359775c93ef37e2f32683
Content-Type: application/json

{
    "content":"sample note",
    "important":"false"
}