GET http://localhost:3001/api/users/

###
POST  http://localhost:3001/api/notes/
Content-Type: application/json
authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkhlbSIsImlkIjoxLCJpYXQiOjE2OTU3MjUwNjJ9.VkiMtnQKuNn6tjK9JsRjcqjPLUaa2Cx_xC9QMwGib68

{
    "content":"This is my own note",
    "important":false
}

###

POST  http://localhost:3001/api/users/
Content-Type: application/json

{
    "username":"Hem1",
    "name":"Hemlal Dulal"
}

###
POST  http://localhost:3001/api/login/
content-type: application/json

{
    "username":"Hem",
    "password":"secret"
}


###
PUT  http://localhost:3001/api/notes/2
Content-Type: application/json

{
    "important":"true"
}