
GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/64d4c66be47aa50c5e8bcd00

###
POST  http://localhost:3001/api/notes
Content-Type: application/json

{
    "content":"Coding practice",
    "important":"false"
}

###
PUT  http://localhost:3001/api/notes/64d359775c93ef37e2f32683
Content-Type: application/json

{
    "content":"sample note",
    "important":"false"
}

###
DELETE http://localhost:3001/api/notes/64d4c66be47aa50c5e8bcd00